[package]
name = "raft-transport"
version = "0.1.0"
edition = "2024"

[dependencies]
wcygan_raft_community_neoeinstein-prost = { workspace = true }
wcygan_raft_community_neoeinstein-tonic = { workspace = true }